// SPDX-License-Identifier: Elastic-2.0

package certify

import (
	"bytes"
	"crypto/ed25519"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
)

// The golden files were generated by SignBuild only after it had been proven
// byte-identical to the two inlined recipes it replaced (previous commit), so
// they pin the bytes both callers signed, not merely SignBuild's own output.
// Ed25519 is deterministic, so the envelope compares exactly.
func TestSignBuildIsTheRecipeBothCallersUsed(t *testing.T) {
	priv := ed25519.NewKeyFromSeed(bytes.Repeat([]byte{7}, 32))
	cases := []struct {
		name  string
		rec   BuildRecord
		dur   float64
		keyID string
	}{
		{"cli", BuildRecord{Repo: "r", Commit: "c", Branch: "b", Actor: "corral-certify",
			Command: "go test ./...", ExitCode: 1, DurationS: SecondsOrUnmeasured(2.5),
			OutputDigest: "sha256:ab", ProducedBy: []string{"corral"}}, 2.5, "corral-certify"},
		{"brain", BuildRecord{Repo: "o/n", Commit: "deadbeef", Branch: "", Actor: "ci-principal",
			Command: "make test", ExitCode: 0, DurationS: SecondsOrUnmeasured(0),
			OutputDigest: "", ProducedBy: []string{"m1", "m2"}}, 0, "brain"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := SignBuild(tc.rec, tc.dur, priv, tc.keyID)
			if err != nil {
				t.Fatal(err)
			}
			gotJSON, err := json.MarshalIndent(map[string]any{
				"head": got.Head, "steps": got.Steps, "statement": got.Statement,
				"canonical": string(got.Canonical), "envelope": string(got.Envelope),
			}, "", "  ")
			if err != nil {
				t.Fatal(err)
			}
			golden := filepath.Join("testdata", "signbuild."+tc.name+".golden")
			if os.Getenv("UPDATE_GOLDEN") != "" {
				if err := os.WriteFile(golden, append(gotJSON, '\n'), 0o600); err != nil {
					t.Fatal(err)
				}
			}
			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatalf("golden missing (regenerate deliberately with UPDATE_GOLDEN=1): %v", err)
			}
			if !bytes.Equal(append(gotJSON, '\n'), want) {
				t.Fatalf("SignBuild drifted from the bytes both callers signed before it existed:\n%s\nwant:\n%s", gotJSON, want)
			}
		})
	}
}
