// SPDX-License-Identifier: Elastic-2.0

package certify

import (
	"bytes"
	"crypto/ed25519"
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

// The golden files were generated by SignBuild only after it had been proven
// byte-identical to the two inlined recipes it replaced (previous commit), so
// they pin the bytes both callers signed, not merely SignBuild's own output.
// Ed25519 is deterministic, so the envelope compares exactly. Regenerated
// ONCE, deliberately, for review f5015cf48e54: an unmeasured duration and
// unrecorded run times are now omitted rather than signed as 0, and that diff
// was read line by line — nothing else moved.
func TestSignBuildIsTheRecipeBothCallersUsed(t *testing.T) {
	priv := ed25519.NewKeyFromSeed(bytes.Repeat([]byte{7}, 32))
	cases := []struct {
		name  string
		rec   BuildRecord
		dur   float64
		keyID string
	}{
		{"cli", BuildRecord{Repo: "r", Commit: "c", Branch: "b", Actor: "corral-certify",
			Command: "go test ./...", ExitCode: 1, DurationS: SecondsOrUnmeasured(2.5),
			OutputDigest: "sha256:ab", ProducedBy: []string{"corral"}}, 2.5, "corral-certify"},
		{"brain", BuildRecord{Repo: "o/n", Commit: "deadbeef", Branch: "", Actor: "ci-principal",
			Command: "make test", ExitCode: 0, DurationS: SecondsOrUnmeasured(0),
			OutputDigest: "", ProducedBy: []string{"m1", "m2"}}, 0, "brain"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := SignBuild(tc.rec, tc.dur, priv, tc.keyID)
			if err != nil {
				t.Fatal(err)
			}
			gotJSON, err := json.MarshalIndent(map[string]any{
				"head": got.Head, "steps": got.Steps, "statement": got.Statement,
				"canonical": string(got.Canonical), "envelope": string(got.Envelope),
			}, "", "  ")
			if err != nil {
				t.Fatal(err)
			}
			golden := filepath.Join("testdata", "signbuild."+tc.name+".golden")
			if os.Getenv("UPDATE_GOLDEN") != "" {
				if err := os.WriteFile(golden, append(gotJSON, '\n'), 0o600); err != nil {
					t.Fatal(err)
				}
			}
			want, err := os.ReadFile(golden)
			if err != nil {
				t.Fatalf("golden missing (regenerate deliberately with UPDATE_GOLDEN=1): %v", err)
			}
			if !bytes.Equal(append(gotJSON, '\n'), want) {
				t.Fatalf("SignBuild drifted from the bytes both callers signed before it existed:\n%s\nwant:\n%s", gotJSON, want)
			}
		})
	}
}

// Review f5015cf48e54#R1: the rule 167dd45b25cc#R1 set for the statement —
// a duration nobody measured is omitted, never signed as 0 — holds for the
// hash-linked execution step too. The statement's subject digest commits to
// that step, so a 0 there was the same false claim one level down.
func TestSignBuildStepOmitsAnUnmeasuredDuration(t *testing.T) {
	priv := ed25519.NewKeyFromSeed(bytes.Repeat([]byte{1}, 32))
	sb, err := SignBuild(BuildRecord{Repo: "r", Commit: "c", Command: "go test"}, 0, priv, "k")
	if err != nil {
		t.Fatal(err)
	}
	if v, present := sb.Steps[1]["detail"].(map[string]any)["duration_s"]; present {
		t.Fatalf("an unmeasured run's execution step signed duration_s=%v", v)
	}
	sb, err = SignBuild(BuildRecord{Repo: "r", Commit: "c", Command: "go test"}, 2.5, priv, "k")
	if err != nil {
		t.Fatal(err)
	}
	if v := sb.Steps[1]["detail"].(map[string]any)["duration_s"]; v != 2.5 {
		t.Fatalf("a measured duration must be signed on the step: %v", v)
	}
}

// Review f5015cf48e54#R2: no caller of SignBuild measures when the build ran,
// and the statement signed startedOn/finishedOn 0 — a claim that it ran at
// the Unix epoch. An unrecorded time is omitted, like an unmeasured duration.
func TestSignBuildOmitsUnrecordedRunTimes(t *testing.T) {
	priv := ed25519.NewKeyFromSeed(bytes.Repeat([]byte{1}, 32))
	sb, err := SignBuild(BuildRecord{Repo: "r", Commit: "c", Command: "go test"}, 2.5, priv, "k")
	if err != nil {
		t.Fatal(err)
	}
	md := sb.Statement["predicate"].(map[string]any)["runDetails"].(map[string]any)["metadata"].(map[string]any)
	for _, k := range []string{"startedOn", "finishedOn"} {
		if v, present := md[k]; present {
			t.Fatalf("signed metadata %s=%v for a run whose times nobody recorded", k, v)
		}
	}
	stmt := BuildAttestation(BuildRecord{Repo: "r", Commit: "c", StartedTS: 100, FinishedTS: 102.5}, "head")
	md = stmt["predicate"].(map[string]any)["runDetails"].(map[string]any)["metadata"].(map[string]any)
	if md["startedOn"] != float64(100) || md["finishedOn"] != 102.5 {
		t.Fatalf("recorded times must be signed: %v", md)
	}
}

// Review f5015cf48e54#R4: SignBuild returns an error; a duration JSON cannot
// carry is refused as one, not a panic from inside BuildLedger.
func TestSignBuildRefusesANonFiniteDuration(t *testing.T) {
	priv := ed25519.NewKeyFromSeed(bytes.Repeat([]byte{1}, 32))
	for _, d := range []float64{math.NaN(), math.Inf(1), math.Inf(-1)} {
		func() {
			defer func() {
				if r := recover(); r != nil {
					t.Fatalf("SignBuild(%v) panicked: %v", d, r)
				}
			}()
			if _, err := SignBuild(BuildRecord{Repo: "r", Commit: "c"}, d, priv, "k"); err == nil {
				t.Fatalf("SignBuild(%v) signed a duration JSON cannot carry", d)
			}
		}()
	}
}
